shop/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path('admin/', admin.site.urls),
    path('user/', include('user.urls', namespace='user')),
    path('', include('store.urls', namespace='store')),
    # path("purchase/", include("purchase.urls", namespace="purchase")),

]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

store/urls.py
from django.urls import path

from store.views import *

app_name = 'store'
urlpatterns = [
    path('<int:pk>/', ProductDetailView.as_view(), name='detail'),
    path('add-to-cart/<slug:slug>/', AddProductToCartView.as_view(), name='add-to-cart'),
    path('', ProductListView.as_view(), name='list'),
    path('purchase/', PurchaseView.as_view(), name='purchase'),
    path("create/", ProductCreateView.as_view(), name="create"),
    path("update/<slug:slug>/", ProductUpdateView.as_view(), name="update"),
    path("delete/<slug:slug>/", ProductDeleteView.as_view(), name="delete"),

]

store/models.py
from django.db import models
from django.urls import reverse_lazy
from django.utils.text import slugify
from django.utils.translation import gettext as _
from django.core.validators import MinValueValidator


# Create your models here.


class ProductBrand(models.Model):
    brand = models.CharField(max_length=20)

    def __repr__(self):
        return f"<ProductBrand [{self.pk}] ('{self}')>"

    def __str__(self):
        return self.brand

    @property
    def name(self):
        return self.brand


class Product(models.Model):
    slug = models.SlugField(
        max_length=128,
        help_text=_('128 characters or fewer.'
                    'Letters, numbers, hyphens and underscores.'),
    )
    product = models.CharField(
        max_length=128,
        verbose_name=_('a product title'),
        help_text=_('128 character or fewer'),
    )
    image = models.ImageField(
        upload_to="static/images",
        default="default/product.png",
    )
    price = models.DecimalField(
        max_digits=10, decimal_places=2,
        validators=[MinValueValidator(0)],
        verbose_name=_('a single product price'),
        help_text=_('a positive number or zero'),
    )
    quantity = models.IntegerField(
        validators=[MinValueValidator(1)],
        help_text=_('a positive integer'),
        default=1,
    )
    description = models.TextField(
        verbose_name=_('product details')
    )
    brand = models.ForeignKey(
        ProductBrand,
        on_delete=models.PROTECT,
        verbose_name=_('product brand')
    )

    def __repr__(self):
        return f"<Product [{self.pk}] ('{self}')>"

    def __str__(self):
        return self.product

    @property
    def name(self):
        """An alias to a product field"""

        return self.product

    def get_absolute_url(self):
        """Return an absolute URL to a product instance"""

        return reverse_lazy("store:detail", kwargs={"pk": self.pk})

    def save(self, *args, **kwargs):
        """Override save method"""

        if not self.slug:
            self.slug = slugify(self.product)

        super(Product, self).save(*args, **kwargs)


class Cart(models.Model):
    user = models.ForeignKey('auth.User', on_delete=models.CASCADE)
    is_active = models.BooleanField(default=True)

    def get_total(self):
        total = 0.0
        for cart_item in self.cart_items.all():
            total = total + cart_item.get.total()
        return total


class CartItem(models.Model):
    product = models.ForeignKey(Product, on_delete=models.PROTECT)
    quantity = models.IntegerField(default=1)
    cart = models.ForeignKey(Cart, on_delete=models.CASCADE, related_name='cart_items')

    def get_total(self):
        return self.product.price * self.quantity


class Purchase(models.Model):
    cart = models.OneToOneField(Cart, on_delete=models.CASCADE)
    user = models.ForeignKey('auth.User', on_delete=models.CASCADE)

store/views.py
from django.http import HttpResponseRedirect
from django.urls import reverse_lazy
from django.views import View
from django.views.generic import ListView, DetailView, RedirectView, CreateView, UpdateView, DeleteView

from store.mixins import StaffRequiredMixin
from store.models import Product, Cart, CartItem


# Create your views here.
class ProductListView(ListView):
    model = Product
    template_name = "store/product_list.html"


class ProductDetailView(DetailView):
    model = Product
    template_name = "store/product_detail.html"


class AddProductToCartView(RedirectView):
    def get(self, *args, **kwargs):
        cart = self.request.session.get('cart', {})
        product_slug = self.kwargs.get('slug')
        if product_slug in cart:
            cart[product_slug] += 1
        else:
            cart[product_slug] = 1
        self.request.session['cart'] = cart
        redirect_url = self.request.headers.get('referer') or reverse_lazy('store:list')
        return HttpResponseRedirect(redirect_url)


class PurchaseView(View):
    def get(self, request, *args, **kwargs):
        session_cart = request.session.get('cart')
        if session_cart is None:
            redirect_url = self.request.headers.get('referer') or reverse_lazy('store:list')
            return HttpResponseRedirect(redirect_url)

        user = self.request.user
        cart = Cart.objects.get_or_create(user=user, is_active=True)

        for product_slug in session_cart:
            product = Product.objects.get(slug=product_slug)
            quantity = session_cart[product_slug]
            cart_item = CartItem(product=product, quantity=quantity, cart=cart)
            cart_item.save()
        self.request.session['cart'] = {}
        redirect_url = self.request.headers.get('referer') or reverse_lazy('store:list')
        return HttpResponseRedirect(redirect_url)


class ProductCreateView(StaffRequiredMixin, CreateView):
    """Product create view implementation"""

    # http_method_names = ["get", "post", "head", "options", "trace"]
    model = Product
    fields = [
        "brand",
        # "image",
        "product",
        "description",
        "price",
        "quantity",
    ]


class ProductUpdateView(StaffRequiredMixin, UpdateView):
    """Product update view implementation"""

    # http_method_names = ["get", "post", "head", "options", "trace"]
    model = Product
    fields = [
        "brand",
        # "image",
        "product",
        "description",
        "price",
        "quantity",
    ]


class ProductDeleteView(StaffRequiredMixin, DeleteView):
    """Product delete view implementation"""

    http_method_names = ["get", "post", "head", "options", "trace"]
    model = Product
    success_url = reverse_lazy("store:list")

store/templates/store/product_confirm_delete.html
{% extends "base.html" %}
{% block doctitle %}Delete Form | {{ block.super }}{% endblock %}
{% block content %}
  <form method="post" class="row justify-content-center">
    {% csrf_token %}
    <div class="col-12">Delete {{ object }} permanently. Are you sure?</div>
    <fieldset>
      <button type="submit" class="btn btn-danger">Submit</button>
      <a href="{{ request.headers.referer }}" class="btn btn-secondary">Cancel</a>
    </fieldset>
  </form>
{% endblock %}

store/templates/store/product_detail.html
{% extends "base.html" %}
{% block content %}
    <div class="row">
        <img src="{{ object.image.url }}" alt="{{ object.slug }}" class="col-6">
        <div class="col-6 justify-content-center">
            <div class="row">
                <h5 class="text">{{ object }}</h5>
            </div>
            <div class="row">
                <span class="text"><b>${{ object.price }}</b></span>
            </div>
            <div class="row">
                {{ object.description|linebreaks }}
            </div>
        </div>
    </div>
    {% if request.user.is_staff %}
        <div class="row">
            <div class="col offset-6">
                <a href="{% url "store:update" slug=object.slug %}" class="btn btn-primary">Update</a>
                <a href="{% url "store:delete" slug=object.slug %}" class="btn btn-danger">Delete</a>
            </div>
        </div>
    {% endif %}
{% endblock %}

store/templates/store/product_form.html
{% extends "base.html" %}
{% load crispy_forms_filters %}
{% block doctitle %}Product Form | {{ block.super }}{% endblock %}
{% block content %}
  <form autocomplete="off" method="post" enctype="multipart/form-data" class="row">
    {% csrf_token %}
    {{ form|crispy }}
    <fieldset>
      <button type="submit" class="btn btn-primary">Submit</button>
      <a
          {% if object %}
            href="{% url "store:detail" pk=object.pk %}"
          {% else %}
            href="{% url "store:list" %}"
          {% endif %}
            class="btn btn-secondary">Cancel</a>
    </fieldset>
  </form>
{% endblock %}

store/templates/store/product_list.html
{% extends "base.html" %}
{% load static %}
{% block content %}
    <div class="row row-cols-1 row-cols-md-3 g-4">
        {% for object in object_list %}
            <div class="col">
                <div class="card">
                    <a href="{% url "store:detail" pk=object.pk %}">
                        <img src="{{ object.image.url }}" class="card-img-top" alt="{{ object.slug }}">
                    </a>
                    <div class="card-body">
                        <h5 class="card-title">{{ object }}</h5>
                        <p class="card-text"><b>${{ object.price }}</b></p>
                        <p class="card-text">{{ object.description|linebreaks }}</p>
                    </div>
                    <div class="card-footer">
                        {% if request.user.is_authenticated %}
                            <form action="#" method="post" class="form-inline mt-1">
                                {% csrf_token %}
                                <input type="hidden" name="product_id" value="{{ object.id }}">
                                <button type="submit" class="btn btn-success">Buy Now</button>
                            </form>
{#                            <form action="{% url "purchase:add" %}" method="post" class="form-inline mt-1">#}
                                {% csrf_token %}
                                <input type="hidden" name="product_id" value="{{ object.id }}">
                                <button type="submit" class="btn btn-secondary">Add to Cart</button>
                            </form>
                        {% endif %}
                        <a href="{% url "store:detail" pk=object.pk %}" class="btn mt-1">View Details</a>
                    </div>
                </div>
            </div>
        {% endfor %}
    </div>
{% endblock %}