shop/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path('admin/', admin.site.urls),
    path('user/', include('user.urls', namespace='user')),
    path('', include('store.urls', namespace='store')),
    # path("purchase/", include("purchase.urls", namespace="purchase")),

]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

store/urls.py
from django.urls import path

from store.views import *

app_name = 'store'
urlpatterns = [
    path('<int:pk>/', ProductDetailView.as_view(), name='detail'),
    path('add-to-cart/<slug:slug>/', AddProductToCartView.as_view(), name='add-to-cart'),
    path('', ProductListView.as_view(), name='list'),
    path('purchase/', PurchaseView.as_view(), name='purchase'),
    path("create/", ProductCreateView.as_view(), name="create"),
    path("update/<slug:slug>/", ProductUpdateView.as_view(), name="update"),
    path("delete/<slug:slug>/", ProductDeleteView.as_view(), name="delete"),

]

user/urls.py
from django.urls import path

from user.views import LogoutView, SignUpView, SignInView, UserProfileView

app_name = 'user'
urlpatterns = [
    path('sign-up/', SignUpView.as_view(), name='sign-up'),
    path('sign-in/', SignInView.as_view(), name='sign-in'),
    path('logout/', LogoutView.as_view(), name='logout'),
    path("profile/", UserProfileView.as_view(), name="profile"),
]

templates/__navbar.html
<nav class="navbar navbar-expand-md navbar-light bg-light fixed-top">
    <div class="container">
        <a class="navbar-brand" href="{% url "store:list" %}">Shop</a>
        <div class="d-block" id="navbarText">
            <ul class="navbar-nav mr-auto">
            <li class="nav-link"><a>Hello, </a>{{ request.user }}</li>


                {#                    <li class="nav-item"><a href="{% url "store:create" %}" class="nav-link">Create</a></li>#}
                {#                {% endif %}#}
                {% if not request.user.is_authenticated %}
                    <li class="nav-item"><a href="{% url "user:sign-in" %}" class="nav-link">Sing In</a></li>
                    <li class="nav-item"><a href="{% url "user:sign-up" %}" class="nav-link">Sing Up</a></li>
                    {#                    <li class="nav-item">#}
                    {#                        <a href="{% url "purchase:checkout" %}" class="nav-link">My Cart#}
                    {#                            {% if cart_entities_count %}#}
                    {#                                <span class="badge bg-dark">{{ cart_entities_count }}</span>#}
                    {#                            {% endif %}#}
                    {#                        </a>#}
                    {#                    </li>#}
                    {#                    <li class="nav-item"><a href="{% url "purchase:list" %}" class=" nav-link">My Purchases</a></li>#}
                    {#                    <li class="nav-item"><a href="{% url "user:profile" %}" class=" nav-link">{{ request.user }}</a>#}
                    {#                    </li>#}

                {% else %}
                    {% if request.user.is_staff %}
                        <li class="nav-item"><a href="admin/" class="nav-link">Admin Page</a></li>
                    {% else %}
                        <li class="nav-item"><a href="#" class="nav-link">My orders</a></li>
                        <li class="nav-item"><a href="#" class="nav-link">My cart</a></li>
                    {% endif %}
                    <li class="nav-item"><a href="{% url "user:logout" %}" class="nav-link">Logout</a></li>
                {% endif %}
            </ul>
        </div>
    </div>
</nav>

templates/_navbar.html
<nav class="navbar navbar-expand-md navbar-light bg-light fixed-top">
    <div class="container">
        <a class="navbar-brand" href="{% url "store:list" %}">My SuperShop</a>
        <div class="d-block" id="navbarText">
            <ul class="navbar-nav mr-auto">
                {% if request.user.is_staff %}
                    <li class="nav-item"><a href="{% url "admin:index" %}" class="nav-link">Admin page</a></li>
{#                    <li class="nav-item"><a href="{% url "store:create" %}" class="nav-link">Create</a></li>#}
                {% endif %}
                {% if request.user.is_authenticated %}
                    <li class="nav-item">
{#                        <a href="{% url "purchase:checkout" %}" class="nav-link">My Cart#}
                            {% if cart_entities_count %}
                                <span class="badge bg-dark">{{ cart_entities_count }}</span>
                            {% endif %}
                        </a>
                    </li>
{#                    <li class="nav-item"><a href="{% url "purchase:list" %}" class=" nav-link">My Purchases</a></li>#}
                    <li class="nav-item"><a href="{% url "user:profile" %}" class=" nav-link">Hello, {{ request.user }}</a>
                    </li>
                    <li class="nav-item"><a href="{% url "user:logout" %}" class="nav-link">Logout</a></li>
                {% else %}
                    <li class="nav-item"><a href="{% url "user:sign-in" %}" class="nav-link">Sing In</a></li>
                    <li class="nav-item"><a href="{% url "user:sign-up" %}" class="nav-link">Sing Up</a></li>
                {% endif %}
            </ul>
        </div>
    </div>
</nav>

templates/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="author" content="Sergey Klimushin <seroga2801@gmail.com>">
    <title>{% block doctitle %}Super shop{% endblock %}</title>

    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1, minimum-scale=1"/>

    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css"
          integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">

    <link rel="stylesheet" type="text/css" href="{% static 'css/main.css' %}">
    {# include bootstrap and custom css #}
    {#    <link rel="stylesheet" href="{% static 'css/main.css' %}">#}
    {#    <link rel="stylesheet" href="{% static "css/ecommerce.css" %}">#}
</head>

<body style="padding-top: 4.5rem">
<header>
    {% block navbar %}
        {% include "_navbar.html" %}
    {% endblock %}
</header>

{# main page content #}
<div class="container">
    {% block content %}{% endblock %}
</div>

{# include bootstrap javascript bundle #}
<script src="https://code.jquery.com/jquery-3.4.1.slim.min.js"
        integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n"
        crossorigin="anonymous"></script>

<script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js"
        integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo"
        crossorigin="anonymous"></script>

<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js"
        integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6"
        crossorigin="anonymous"></script>
</body>
</html>

</body>

</html>